spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema:
        registry:
          cache-capacity: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_CACHE_CAPACITY}
          url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL}
    topic:
      user-events: ${SPRING_KAFKA_TOPIC_USER_EVENTS}
      user-events-dlt: ${SPRING_KAFKA_TOPIC_USER_EVENTS_DLT}
      auth-server-events: ${SPRING_KAFKA_TOPIC_AUTH_SERVER_EVENTS}
    producer-avro:
      key-serializer: ${SPRING_KAFKA_PRODUCER_AVRO_KEY_SERIALIZER}
      value-serializer: ${SPRING_KAFKA_PRODUCER_AVRO_VALUE_SERIALIZER}
    producer-dlt:
      key-serializer: ${SPRING_KAFKA_PRODUCER_DLT_KEY_SERIALIZER}
      value-serializer: ${SPRING_KAFKA_PRODUCER_DLT_VALUE_SERIALIZER}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      key-deserializer: ${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER}
      value-deserializer: ${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER}
      properties:
        spring.deserializer.key.delegate.class: ${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_DESERIALIZER_KEY_DELEGATE_CLASS}
        spring.deserializer.value.delegate.class: ${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_DESERIALIZER_VALUE_DELEGATE_CLASS}
        spring.json.trusted.packages: ${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES}
        spring.json.value.default.type: ${SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE}
management:
  endpoints:
    web:
      exposure:
        include: ${SPRING_MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
server:
  port: ${SPRING_SERVER_PORT}